In [1]:
'''
#A2-Q1 
#Creating a matrix class that will facilitate the handling for matrices for any dimension
The matrix class will take input in list of lists format, e.g., the matrix 
[1 0 0] will be entered as [[1,0,0],[0,1,0],[0,0,1]]
[0 1 0]
[0 0 1]
'''
class Matrix:
    def __init__(self,list_of_lists):
        for i in range(len(list_of_lists)):
            if len(list_of_lists[i]) != len(list_of_lists[0]): #It must be a matrix afterall
                print("undefined matrix")
        self.lol=list_of_lists
    def show(self):#Method to display the matrix appropriately
        for i in self.lol:
            for j in i:
                print(str(j)+str(','),end='')
            print("\n")
    def Transpose(self):#Method defining the Transpose of a matrix
        C=[]
        for _ in range(len(self.lol[0])):#Inverting the number of rows and columns
            C+=[[]]
        for i in range(len(self.lol)):
            for j in range(len(self.lol[i])):#appending the rows as columns
                C[j].append(self.lol[i][j])
        return(Matrix(C))
def Mat_product(X,Y,show=True):
    if isinstance(X,Matrix) == True and isinstance(Y,Matrix) ==True:
#Just a check to see if the matrices can be actually be multiplied
        if len(X.lol[0])!=len(Y.lol):
            print('Product not defined')
        else:
            m=len(X.lol)
            n=len(Y.lol[0])
            Z=[]
            for _ in range(m):#creating the new matrix
                Z+=[[]]
            for i in range(len(X.lol)):#populating the entries of the new matrix
                temp=0
#The next three lines multiply the necessary elements to find the i,l th element of the new matrix
                for l in range(len(Y.lol[0])):
                    for j in range(len(X.lol[i])):
                        temp+=X.lol[i][j]*Y.lol[j][l]
                    Z[i].append(temp)
                    temp=0
            if show==True:
                Matrix(Z).show()
            return(Matrix(Z))
    else:
        print("Not a matrix")

In [2]:
'''
#A function to read the data from the files to obtain the matrix
#The file must be created in the following format, 
    #only one row must be written in a line, with elements separated by commas,
    #no comma is allowed to be placed at the end of a line except when the line describes the last row
    #Comma at the end of the last row is necessary
    #[1 0 0] is entered as 1,0,0
     [0 1 0]               0,1,0 <-note the absence of comma
     [0 0 1]               0,0,1,<- note this comma
    #
'''
def read_matrix(file_name):
    file=open(str(file_name),"r")
    M=[[]]
    temp=''
    i=0
#what follows below is a just accessing the strings one by one, and and converting the file data to list
#of lists format
    for j in file:
        for k in j:
            if k=='\n':
                M[i]+=[int(temp)]
                temp=''
                i+=1
                M+=[[]]
            elif k!=',' and k!='\n':
                temp+=k
            elif k==',':
                M[i]+=[int(temp)]
                temp=''
    return(M)
    

In [3]:
#Reading the matrices from their files
A=Matrix(read_matrix('A.txt'))
B=Matrix(read_matrix('B.txt'))
C=Matrix(read_matrix('C.txt'))
D=Matrix(read_matrix('D.txt'))

In [4]:
A.show()

2,3,4,

1,0,0,

6,5,4,



In [5]:
B.show()

3,4,7,

9,0,2,

5,3,8,



In [6]:
C.show()

1,2,3,



In [7]:
D.show()

6,3,1,



In [8]:
#Taking the dot product of the vectors C and D
Mat_product(C,D.Transpose())

15,



In [9]:
#Multiplying the matrices A and B
Mat_product(A,B)

53,20,52,

3,4,7,

83,36,84,



In [10]:
#Multiplying the matrices C and A
Mat_product(C,A)

22,18,16,



In [11]:
#Multiplying the matrices D and B
Mat_product(D,B)

50,27,56,



In [12]:
E=Matrix(read_matrix('E.txt'))
Mat_product(E,C)

1,2,3,

2,4,6,

3,6,9,



In [13]:
'''
A2-Q2
#Defining a complex number class with the important complex numbers' properties 
'''
class myComplex:
    def __init__(self,x,y):
        self.real=x
        self.imaginary=y
    def conjugate(self):
        return(myComplex(self.real,-self.imaginary))
    def modulus(self):
        return((self.real**2+self.imaginary**2)**(1/2))
    def phase(self):
#The phase defined here is from -pi to pi, NOT 0 to 2*pi
        import math #To be able to calculate arctan
        theta=math.atan(abs(self.imaginary/self.real))
#The following if-else loop calculates the phase in -pi to pi
        if self.real>0 and self.imaginary>0:
            return(theta)
        elif self.real<0 and self.imaginary>0:
            return(math.pi-theta)
        elif self.real>0 and self.imaginary<0:
            return(-theta)
        elif self.real<0 and self.imaginary<0:
            return(theta-math.pi)
    def show(self):#a method to show the complex numbers obtained
        print('('+str(self.real)+')'+'+'+'('+str(self.imaginary)+')i')

#A function to multiply two complex numbers
def comp_product(c1,c2):
    if isinstance(c1,myComplex)==True and isinstance(c2,myComplex)==True:#Just to make sure if the inputs are complex
        return(myComplex(c1.real*c2.real-c1.imaginary*c2.imaginary,c1.real*c2.imaginary+c2.real*c1.imaginary))
    else:
        print("Both inputs must be complex")

#A function to add two complex numbers
def comp_sum(c1,c2):
    if isinstance(c1,myComplex)==True and isinstance(c2,myComplex)==True:#Just to make sure if the inputs are complex
        return(myComplex(c1.real+c2.real,c1.imaginary+c2.imaginary))
    else:
        print("Both inputs must be complex")

#A function to divide two complex numbers
def comp_div(c1,c2):
    if isinstance(c1,myComplex)==True and isinstance(c2,myComplex)==True:#Just to make sure if the inputs are complex
        return(myComplex(comp_product(c1,c2.conjugate()).real/(c2.modulus())**2,comp_product(c1,c2.conjugate()).imaginary/(c2.modulus())**2))
    else:
        print("Both inputs must be complex")

In [14]:
#Defining two complex numbers
z1=myComplex(1,-2)
z2=myComplex(2,3)

In [15]:
z1.show()

(1)+(-2)i


In [16]:
z1.conjugate().show()

(1)+(2)i


In [17]:
z1.phase()

-1.1071487177940904

In [18]:
comp_div(z1,z2).show()

(-0.3076923076923077)+(-0.5384615384615385)i


In [19]:
comp_product(z1,z2).show()

(8)+(-1)i


In [20]:
comp_sum(z1,z2).show()

(3)+(1)i


In [21]:
#A2-Q3
#Average distance between two points on a line of N equally spaced points
def av_dist(N):
    m=0
    dist_sum=0
    for i in range(N):#choosing a reference point
        for j in range(N):#choosing another point, which may or may not be the reference point
            m+=1    #increasing the number of distances calculated
            dist_sum+=abs(j-i) #calculating the distance
    return(dist_sum/(m)) #Finding the average


In [22]:
for i in range(1,11):
    print('Average distance on a line of '+str(i)+' point(s) is '+str(av_dist(i)))

Average distance on a line of 1 point(s) is 0.0
Average distance on a line of 2 point(s) is 0.5
Average distance on a line of 3 point(s) is 0.8888888888888888
Average distance on a line of 4 point(s) is 1.25
Average distance on a line of 5 point(s) is 1.6
Average distance on a line of 6 point(s) is 1.9444444444444444
Average distance on a line of 7 point(s) is 2.2857142857142856
Average distance on a line of 8 point(s) is 2.625
Average distance on a line of 9 point(s) is 2.962962962962963
Average distance on a line of 10 point(s) is 3.3


In [23]:
'''
A2-Q4
#Designing a Hangman game
'''
#This is a letter search algorithm which returns the indices that a particular letter occupies in a string
def letter_search(letter,string):
    indices=[]
    for i in range(len(string)):
        if string[i].lower() == letter.lower():
            indices.append(i)
    return(indices)

In [24]:
def play_Hangman():
    #The Names that are to be guessed by the player
    Names=['Aarav','Mohammed','Vihaan','Aditya','Sai','Arjun','Aryan','Reyansh','Vivaan','Krishna','Atharv','Ayaan','Ishaan','Dhruv','Ryan','Arnav','Shaurya','Kabir','Aarush','Rudra','Ayush','Advik','Ansh','Sathvik']
    #Importing random to randomly select a name
    import random
    n=random.randint(0,23)
    #Number of wrong guesses is 40% of the word length
    guess_lft=int(len(Names[n])*2/5)
    print("Welcome to Hangman: 2021")
    unK="?"*len(Names[n])#Unknown name
    print("Your word is: "+unK)
    print("You can make at most "+str(guess_lft)+" wrong guesses")
    print("Please enter only one character at a time")
    while True:
        let=input('Guess a letter of the name: ')
        if len(let)==1:#player can enter only one character at a time
            indices=letter_search(let,Names[n])
            if len(indices)>0:#correct guess
                for i in indices:
                    unK=unK[:i]+let+unK[i+1:] # revealing the position of the correctly guessed letter
                print("Correct guess! The word is: "+unK+"\t\twrong guesses left: "+str(guess_lft))
                if len(letter_search('?',unK)) ==0:
                    print("Congratulations, You won!")#Nothing left to reveal, thus winning the game
                    break
            else:#wrong guess
                guess_lft=guess_lft-1
                if guess_lft<0:
                    print("You lost! the correct word is "+Names[n])#no wrong guesses left
                    break
                print(let+" is a wrong guess! The word is: "+unK+"\t\t\twrong guesses left: "+str(guess_lft))
        else:
            print("Enter only a single letter!")

In [25]:
play_Hangman()

Welcome to Hangman: 2021
Your word is: ?????
You can make at most 2 wrong guesses
Please enter only one character at a time
Correct guess! The word is: ????a		wrong guesses left: 2
Correct guess! The word is: r??ra		wrong guesses left: 2
Correct guess! The word is: r?dra		wrong guesses left: 2
Correct guess! The word is: rudra		wrong guesses left: 2
Congratulations, You won!


In [26]:
play_Hangman()

Welcome to Hangman: 2021
Your word is: ????
You can make at most 1 wrong guesses
Please enter only one character at a time
Correct guess! The word is: ??a?		wrong guesses left: 1
Correct guess! The word is: r?a?		wrong guesses left: 1
Correct guess! The word is: rya?		wrong guesses left: 1
Correct guess! The word is: ryan		wrong guesses left: 1
Congratulations, You won!


In [29]:
play_Hangman()

Welcome to Hangman: 2021
Your word is: ??????
You can make at most 2 wrong guesses
Please enter only one character at a time
Correct guess! The word is: a??a??		wrong guesses left: 2
Correct guess! The word is: at?a??		wrong guesses left: 2
Correct guess! The word is: atha??		wrong guesses left: 2
Correct guess! The word is: athar?		wrong guesses left: 2
Correct guess! The word is: atharv		wrong guesses left: 2
Congratulations, You won!


In [28]:
play_Hangman()

Welcome to Hangman: 2021
Your word is: ???????
You can make at most 2 wrong guesses
Please enter only one character at a time
Correct guess! The word is: ?a?????		wrong guesses left: 2
m is a wrong guess! The word is: ?a?????			wrong guesses left: 1
b is a wrong guess! The word is: ?a?????			wrong guesses left: 0
You lost! the correct word is Sathvik


In [30]:
play_Hangman()

Welcome to Hangman: 2021
Your word is: ???????
You can make at most 2 wrong guesses
Please enter only one character at a time
Correct guess! The word is: ??????a		wrong guesses left: 2
m is a wrong guess! The word is: ??????a			wrong guesses left: 1
b is a wrong guess! The word is: ??????a			wrong guesses left: 0
Correct guess! The word is: ??i???a		wrong guesses left: 0
Correct guess! The word is: ?ri???a		wrong guesses left: 0
Correct guess! The word is: ?ris??a		wrong guesses left: 0
You lost! the correct word is Krishna


In [31]:
play_Hangman()

Welcome to Hangman: 2021
Your word is: ????
You can make at most 1 wrong guesses
Please enter only one character at a time
Correct guess! The word is: ??a?		wrong guesses left: 1
m is a wrong guess! The word is: ??a?			wrong guesses left: 0
You lost! the correct word is Ryan


In [ ]:
'''
['Aarav','Mohammed','Vihaan','Aditya','Sai','Arjun','Aryan','Reyansh','Vivaan','Krishna','Atharv','Ayaan','Ishaan'
,'Dhruv','Ryan','Arnav','Shaurya','Kabir','Aarush','Rudra','Ayush','Advik','Ansh','Sathvik']
'''
#The list of names used for reference